### ISSUE TITLE
Setting multi-line variable only works in bash, so change setting GitHub release notes to bash

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/azure-devops-templates#53]
**Describe the bug**
Setting a multi-line variable only works in bash (actually a workaround, as it doesn't work in PowerShell).

**To Reproduce**
* Look at the GitHub releases pipeline, the multi-line value is not send to the GitHub release notes, only the first line.

**Expected behavior**
We should have a fully ready GitHub release with the titles automatically.

**Comment by fgheysels** [comment]
I believe this has something to do with the 'line-separator' character that you use ?
More info might be found [here](https://stackoverflow.com/questions/57562449/how-to-split-a-cli-command-in-azure-devops-over-multiple-lines-running-on-wind/70263672#70263672)

**Comment by stijnmoreels** [comment]
> I believe this has something to do with the 'line-separator' character that you use ? More info might be found [here](https://stackoverflow.com/questions/57562449/how-to-split-a-cli-command-in-azure-devops-over-multiple-lines-running-on-wind/70263672#70263672)

It's a multi-line string, so not a command. We want to set such a multi-line string via a `[vso.setvariable` write to the console, but only the first line is there, so the value is already multi-line, it's just that the Azure DevOps in PowerShell does not seem to handle this correctly and in Bash it does handle it correctly.
